export const projects = [
  {
    title: 'Pet Paws',
    description: "I developed Pet Paws - an open-source application - that gathers the pets available for adoption in its vicinity, providing users with the facility to do a good deed and contribute to reducing mistreatment. I'd like to give a shout-out to Rafael, who contributed a lot during the process.",
    image: '/images/petpaws.jpeg',
    tags: ['React', 'Express', 'Node.js'],
    source: 'https://github.com/naomilago/Pet-Paws',
    visit: 'https://github.com/naomilago/Pet-Paws',
    id: 0,
  },
  {
    title: 'Healthier',
    description: "Healthier is also a very special project because I could deal with UX/UI Design, which is another thing I love. It consists of an application that helps you find better ways to have healthy meals, good recipes and tips for living a healthier life. When I came up with this idea I got so excited and I had a good time designing it. PS.: Healthier is still a prototype until now. Feel free to develop the application as you want, as long as you keep it free and open-source 😊",
    image: '/images/healthier.jpeg',
    tags: ['Figma'],
    source: 'https://www.figma.com/file/ARY6RmJYci18Ss9mwBWmEm/Naomi-Lago-Healthier-1.0',
    visit: 'https://www.figma.com/file/ARY6RmJYci18Ss9mwBWmEm/Naomi-Lago-Healthier-1.0',
    id: 1,
  },
  {
    title: 'Be the Hero',
    description: "I developed Be the Hero during an event organized by Rocketseat and it is an open-source project. The idea is to build bridges between NGOs and people who want to contribute to them. Users can access many fundings and choose which one they will contribute while the organizations can register many fundings based on their activities.",
    image: '/images/bethehero.jpeg',
    tags: ['React', 'React Native', 'Express', 'Node.js'],
    source: 'https://github.com/naomilago/BeTheHero',
    visit: 'https://github.com/naomilago/BeTheHero',
    id: 2,
  },
  {
    title: "Naomi's Mailling",
    description: "This is a mailling project, where you can create multiple discussion lines with dozens of subscribers, write ad-hoc SQL queries to search, create dinamic e-mails templates using a WYSIWYG, and so on.",
    image: '/images/mailling.jpeg',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/naomilago/NaomisMailing',
    visit: 'https://mailling.netlify.app/',
    id: 3,
  },
  {
    title: 'Findy',
    description: "Findy is another open-souce web application and it works like a search engine. It finds news, images and videos related to your search and shows you in a beautiful way.",
    image: '/images/findy.jpeg',
    tags: ['React', 'Tailwind CSS', 'Node.js'],
    source: 'https://naomilago-findy.netlify.app/',
    visit: 'https://naomilago-findy.netlify.app/',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey', },
  { year: 2019, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];